#!/bin/bash
# Pre-mark the VS Code desktop shortcut as trusted, so double-clicking it doesn't
# trigger xfce's "untrusted launcher" prompt.
f=/home/jovyan/Desktop/code.desktop
gio set -t string "$f" metadata::xfce-exe-checksum "$(sha256sum "$f" | awk '{print $1}')"
