name: linting

on: [push]

env:
  UV_SYSTEM_PYTHON: true

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install package
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv pip install --no-deps .
          uv pip install -r dev-requirements.txt
      - name: ruff check
        run: |
          ruff check src/pynxtools_mpes tests
      - name: ruff format
        run: |
          ruff format --check src/pynxtools_mpes tests
      - name: mypy
        run: |
          mypy src/pynxtools_mpes tests
